### ISSUE TITLE
not working for subdomain 

### ISSUE THREAD

**Issue by Irtizashahid** [GenomeUS/keystone-express-sitemap#1]
I have a blog on my subdomain blog.example.com  "keystone-express-sitemap" is not working fine for me .In sitemap.xml it display domain name only not subdomain .

```
 <url>
<loc>http://example.com/blog/post/transporter-un-bateau</loc>
</url>
```

What i want 

```
 <url>
<loc>http://blog.example.com/blog/post/transporter-un-bateau</loc>
</url>
```

**Comment by s-plum** [comment]
Which versions of Keystone and Express are you using?

**Comment by Irtizashahid** [comment]
Thank dear for your response ....i am using latest version of both Keystone and Express ....I have resolved above issue by changing Hostname in keystone.js file ...it was example.com after changing it to blog.example.com, issue resolved :) .
